// <auto-generated />
using DGII.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGII.Migrations
{
    [DbContext(typeof(DGIIContext))]
    [Migration("20240413232731_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DGII.Model.TaxPayer", b =>
                {
                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "rncCedula");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "estatus");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo");

                    b.HasKey("TaxId");

                    b.ToTable("TaxPayers");
                });

            modelBuilder.Entity("DGII.Model.TaxReceipt", b =>
                {
                    b.Property<string>("TaxReceiptNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "NCF");

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.Property<float>("TaxAmount")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "itbis18");

                    b.Property<string>("TaxPayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "rncCedula");

                    b.HasKey("TaxReceiptNumber");

                    b.ToTable("TaxReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
